### PR TITLE
Fix error for using vineyard-graph-loader with multi-workers.

### LINKED ISSUE #1602: Wrong edges when loading graph incrementally within multi workers
Describe your problem
---------------------

Using below commond to load graph incrementally. And we can see a different edge result from loading the whole graph directly.
```bash
mpiexec -n 2 vineyard-graph-loader ...
```

### PR DESCRIPTION
**Pull request by SighingSnow**
What do these changes do?
-------------------------

Fix the wrong result when using  vineyard-graph-loader incrementally with multi-workers.

Related issue number
--------------------

Fixes #1602

### CODE REVIEW

**Comment by sighingnow** [comment]
Thanks for debugging and fixing! Could you please format the code to conform to the CI requirement?

**Comment by SighingSnow** [comment]
> Thanks for debugging and fixing! Could you please format the code to conform to the CI requirement?

I haven't solve this issue completely. I will format the code after that. Thanks for reminding!

**Comment by SighingSnow** [comment]
@siyuan0322  would you mind to help me review the code.

**Review by siyuan0322 — APPROVED** [review]

File: modules/graph/fragment/arrow_fragment_builder_impl.h [hunk 1]
```diff
@@ -1009,19 +1013,45 @@ ArrowFragment<OID_T, VID_T, VERTEX_MAP_T, COMPACT>::AddEdgesToExistedLabel(
...
         }
       }
+      if (directed_) {
+        auto ie = this->GetIncomingAdjList(v, label_id);
+        for (auto& e : ie) {
+          auto dst_label = vertex_label(e.neighbor());
+          auto dst_offset = vertex_offset(e.neighbor());
+          vid_t dst_id = vid_parser_.GenerateId(dst_label, dst_offset);
+          if (vis.count(std::to_string(dst_id) + std::to_string(src_id)))
+            continue;
```
[the remark this answers is not in the document]
Comment (SighingSnow) [reply modules/graph/fragment/arrow_fragment_builder_impl.h:1035]: Yes of course. Thanks a lot.

[the remark this answers is not in the document]
Comment (SighingSnow) [reply modules/graph/fragment/arrow_fragment_builder_impl.h:1035]: I will push a new commit later.

File: modules/graph/test/arrow_fragment_extend_test.cc [hunk 2]
```diff
@@ -0,0 +1,291 @@
...
+            frag_id = loader->AddDataToExistedELabel(frag_id, 0).value();
+            test_frag_group =
+                ConstructFragmentGroup(client, frag_id, comm_spec).value();
+          }
+        }
+      }
+    }
+
+    bool valid =
+        Validation(client, comm_spec, true_frag_group, test_frag_group);
```
Comment (siyuan0322) [inline modules/graph/test/arrow_fragment_extend_test.cc:281]: Call this `Validate`

File: test/runner.py [hunk 3]
```diff
@@ -494,6 +521,7 @@ def run_graph_tests(meta, allocator, endpoints, tests):
         ['--allocator', allocator],
         default_ipc_socket=VINEYARD_CI_IPC_SOCKET,
     ) as (_, rpc_socket_port):
+        run_graph_extend_test(tests)
```
Comment (siyuan0322) [inline test/runner.py:524]: Put this after arrow fragment test, since the test order should from simple to complex

File: modules/graph/fragment/arrow_fragment_builder_impl.h [hunk 4]
```diff
@@ -996,32 +1000,64 @@ ArrowFragment<OID_T, VID_T, VERTEX_MAP_T, COMPACT>::AddEdgesToExistedLabel(
     for (auto v : iv) {
       auto offset = vertex_offset(v);
       vid_t src_id = vid_parser_.GenerateId(v_label, offset);
-      // if(!directed_ && vis.count(src_id)) continue;
       auto oe = this->GetOutgoingAdjList(v, label_id);
-      // if(oe.Size()) prev_src_ids.push_back(src_id);
       for (auto& e : oe) {
         auto dst_label = vertex_label(e.neighbor());
         auto dst_offset = vertex_offset(e.neighbor());
         vid_t dst_id = vid_parser_.GenerateId(dst_label, dst_offset);
```
Comment (siyuan0322) [inline modules/graph/fragment/arrow_fragment_builder_impl.h:1007]: Declare "std::to_string(src_id) + std::to_string(dst_id)" and "std::to_string(dst_id) + std::to_string(src_id)" at the beginning of the loop, to avoid concat them again and again, also improves readability

**Review by siyuan0322 — APPROVED** [review]

File: modules/graph/test/arrow_fragment_extend_test.cc [hunk 5]
```diff
@@ -0,0 +1,291 @@
...
+    for (int j = 0; j < true_ivs[i].size(); ++j) {
+      if (true_ivs[i][j] != test_ivs[i][j]) {
+        LOG(INFO) << "ground-truth v is " << true_ivs[i][j] << "and program is "
+                  << test_ivs[i][j];
+        return false;
+      }
+    }
+    for (int j = 0; j < true_ies[i].size(); ++j) {
+      if (true_ies[i][j] != test_ies[i][j]) {
+        LOG(INFO) << "different inner edge";
```
Comment (siyuan0322) [inline modules/graph/test/arrow_fragment_extend_test.cc:144]: use LOG(ERROR)
