### PR TITLE
Delete the retry logic while launching metadata service and reset the etcd client while probing

### LINKED ISSUE #1648: The `segmentation fault` error occurs while the vineyardd waiting for metadata service.
Describe your problem
---------------------

The `segmentation fault` error occurs while the vineyardd waiting for metadata service.

Reproduce steps.
1. Launch the latest vineyardd with the following flags.
```shell
./bin/vineyardd --etcd_endpoint=http://an-unknown-hostname:2379
```

2. Get the `segmentation fault` error as follows.
```bash
./bin/vineyardd --etcd_endpoint=http://an-unknown-hostname:2379
I1214 10:49:18.251545 1367702 vineyardd.cc:104] Hello vineyard v0.19.1!
I1214 10:49:18.259234 1367702 meta_service.h:96] meta service is starting, waiting the metadata backend service becoming ready ...
*** Aborted at 1702522158 (unix time) try "date -d @1702522158" if you are using GNU date ***
PC: @     0x558f28a12d34 etcd::Client::ls()
*** SIGSEGV (@0x8) received by PID 1367702 (TID 0x7f94d9ffd980) from PID 8; stack trace: ***
    @     0x7f94de5ce631 (unknown)
    @     0x7f94dbd4f420 (unknown)
    @     0x558f28a12d34 etcd::Client::ls()
    @     0x558f288c8ad6 vineyard::EtcdLauncher::probeEtcdServer()
    @     0x558f28895b3e vineyard::EtcdMetaService::probe()
    @     0x558f28860298 vineyard::IMetaService::Start()
    @     0x558f288381da vineyard::VineyardServer::Serve()
    @     0x558f2882452b vineyard::VineyardRunner::Serve()
    @     0x558f28953afe main
    @     0x7f94db4d2083 __libc_start_main
    @     0x558f2869c94e _start
[1]    1367702 segmentation fault  ./bin/vineyardd --etcd_endpoint=http://an-unknown-hostname:2379
```

### PR DESCRIPTION
**Pull request by dashanji**
What do these changes do?
-------------------------

As titled.

Related issue number
--------------------

Fixes #1648

### CODE REVIEW

File: src/server/services/etcd_meta_service.cc [hunk 1]
```diff
@@ -380,9 +380,15 @@ void EtcdMetaService::retryDaeminWatch(
...
 Status EtcdMetaService::probe() {
+  std::string const& etcd_endpoint =
+      etcd_spec_["etcd_endpoint"].get_ref<std::string const&>();
+  if (etcd_ == nullptr) {
+    etcd_.reset(new etcd::Client(etcd_endpoint));
+  }
   if (EtcdLauncher::probeEtcdServer(etcd_, prefix_)) {
     return Status::OK();
   } else {
+    etcd_.reset(new etcd::Client(etcd_endpoint));
```
Comment (sighingnow) [inline src/server/services/etcd_meta_service.cc:391]: Why you need this initialization?

Comment (dashanji) [reply src/server/services/etcd_meta_service.cc]: Done. Reset the client before probing.

**Review by sighingnow — APPROVED** [review]
